# Python CircleCI 2.0 configuration file
# vi: et:ts=2:sw=2
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: quay.io/pypa/manylinux1_x86_64
    working_directory: ~/python-mbedtls
    steps:
      - checkout
      - run:
          name: Setup environment
          command: |
            cat << 'EOF' >> $BASH_ENV
            _bin="/opt/python/cp36-cp36m/bin"
            pip="$_bin/python -m pip"
            tox="$_bin/python -m tox"
            EOF
      - run:
          name: Install mbedtls
          command: |
            yum -yq install wget cmake
            ./install-mbedtls.sh 2.7.0 /usr/local
            # FIXME: 2.7.2 rejects CRLs with unsupported critical extensions.
            #        I need to replace the canned certificate.
      - run:
          name: Install dev environment
          command: |
            $pip install -r requirements-dev.txt
      - run:
          name: Test Python 2.7 wide unicode
          command: |
            version="cp27-cp27mu"
            PATH="/opt/python/$version/bin:$PATH"
            python setup.py bdist_wheel 1> /dev/null
            auditwheel repair dist/*$version*.whl
            $tox -e py27 --installpkg wheelhouse/*$version*.whl
      - run:
          name: Test Python 3.4
          command: |
            version="cp34-cp34m"
            PATH="/opt/python/$version/bin:$PATH"
            python setup.py bdist_wheel 1> /dev/null
            auditwheel repair dist/*$version*.whl
            $tox -e py34 --installpkg wheelhouse/*$version*.whl
      - run:
          name: Test Python 3.5
          command: |
            version="cp35-cp35m"
            PATH="/opt/python/$version/bin:$PATH"
            python setup.py bdist_wheel 1> /dev/null
            auditwheel repair dist/*$version*.whl
            $tox -e py35 --installpkg wheelhouse/*$version*.whl
      - run:
          name: Test Python 3.6
          command: |
            version="cp36-cp36m"
            PATH="/opt/python/$version/bin:$PATH"
            python setup.py bdist_wheel 1> /dev/null
            auditwheel repair dist/*$version*.whl
            $tox -e py36 --installpkg wheelhouse/*$version*.whl
      - run:
          name: Test Python 3.7
          command: |
            version="cp37-cp37m"
            PATH="/opt/python/$version/bin:$PATH"
            python setup.py bdist_wheel 1> /dev/null
            auditwheel repair dist/*$version*.whl
            $tox -e py37 --installpkg wheelhouse/*$version*.whl
      - deploy:
          name: Distribute
          command: |
            ls dist/*
            ls wheelhouse/*
            # XXX Make sdist as well!
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              echo "[pypi]" > $HOME/.pypirc
              echo "username = Synss" >> $HOME/.pypirc
              echo "password = $PYPI_PASSWORD" >> $HOME/.pypirc
              twine upload wheelhouse/*
            fi
          when: on_success
      - run:
          name: Save logs
          command: |
            mkdir -p logs
            cp .tox/*/log/py*.log logs || true
          when: on_fail
      - store_artifacts:
          path: logs
          destination: artifacts
      - store_artifacts:
          path: wheelhouse
          destination: wheelhouse
